//more key codes here: http://msdn.microsoft.com/en-us/library/aa243025%28v=vs.60%29.aspx
const KEY_BACKSPACE	= 8;
const KEY_TAB		= 9;
const KEY_RETURN	= 13;
const KEY_ESC		= 27;
const KEY_LEFT		= 37;
const KEY_UP		= 38;
const KEY_RIGHT		= 39;
const KEY_DOWN		= 40;